#include <cstdio>                    //( 1)
using namespace std;                 //( 2)
extern "C" double mnoz(int n,        //( 3)
   double * a, double *b, double w); //( 4)
                                     //( 5)
int main(){                          //( 6)
 const int n = 4;                    //( 7)
 double x[] = {1., 2., 3., 6.};      //( 8)
 double y[] = {-1., 4., 3., -1.};    //( 9)
 double w = 3.0;                     //(10)
 printf("%lf \n", mnoz(n, x, y, w)); //(11)
 return 0;                           //(12)
}                                    //(13)
