section .text              ;( 1)
global podwoj, mnoz        ;( 2)
                           ;( 3)
podwoj:                    ;( 4)
  movsd [rsp-24], xmm0     ;( 5)
  movsd [rsp-16], xmm0     ;( 6)
  movapd xmm0, [rsp-24]    ;( 7)
  ret                      ;( 8)
                           ;( 9)
mnoz:                      ;(10)
  push rbx                 ;(11)
  call podwoj              ;(12)
  pxor xmm1, xmm1          ;(13)
  jmp .check               ;(14)
.loop:                     ;(15)
  movupd xmm2, [rsi+8*rdi] ;(16)
  movupd xmm3, [rdx+8*rdi] ;(17)
  subpd  xmm2, xmm0        ;(18)
  subpd  xmm3, xmm0        ;(19)
  mulpd  xmm2, xmm3        ;(20)
  addpd  xmm1, xmm2        ;(21)
.check:                    ;(22)
  sub rdi, 2               ;(23)
  jns .loop                ;(24)
  movapd xmm0, xmm1        ;(25)
  haddpd xmm0, xmm1        ;(26)
  pop rax                  ;(27)
  ret                      ;(28)
