#include <stdio.h>                               //( 1)
double wylicz(double a, double b, double c,      //( 2)
              double d, double e, double * max); //( 3)
int main(){                                      //( 4)
  register int a = 1;                            //( 5)
  double max=0.0, wynik=0.0;                     //( 6)
  wynik = wylicz(1, -2, 3, -4, 5, &max);         //( 7)
  printf("%f | %f\n", wynik , max );             //( 8)
  wynik = wylicz(1.5, 2, -3.5, 4., 5.5, &max);   //( 9)
  printf("%f | %f\n", wynik, max );              //(10)
  wynik = wylicz(-1, -2, -3, -4, -5, &max);      //(11)
  printf("%f | %f\n", wynik, max );              //(12)
  printf("%d\n", a);                             //(13)
}                                                //(14)
