BITS 64                              ;( 1)
section .text                        ;( 2)
global _Z8przeliczii, _Z8przeliczdd, ;( 3)
global _Z8przeliczPKdS0_             ;( 4)
                                     ;( 5)
_Z8przeliczii:                       ;( 6)
  mov eax, edi                       ;( 7)
  mov ecx, esi                       ;( 8)
.petla:                              ;( 9)
  xor rdx, rdx                       ;(10)
  idiv ecx                           ;(11)
  test edx, edx                      ;(12)
  jz .koniec                         ;(13)
  mov eax, ecx                       ;(14)
  mov ecx, edx                       ;(15)
  jmp .petla                         ;(16)
.koniec:                             ;(17)
  mov eax, ecx                       ;(18)
  pop rbx                            ;(19)
  jmp rbx                            ;(20)
                                     ;(21)
_Z8przeliczdd:                       ;(22)
  enter 16,0                         ;(23)
  movsd [rbp-16], xmm0               ;(24)
  fld qword [rsp]                    ;(25)
  fmul st0                           ;(26)
  movsd [rsp], xmm1                  ;(27)
  fld qword [rbp-16]                 ;(28)
  fmul st0
  ;fld qword [rbp-16]                           ;(29)
  fsubp                              ;(30)
  fstp qword [rsp]                   ;(31)
  movsd xmm0, [rsp]                  ;(32)
  leave                              ;(33)
  ret                                ;(34)
                                     ;(35)
_Z8przeliczPKdS0_:                   ;(36)
  movsd xmm0, [rdi]                  ;(37)
  movsd xmm1, [rsi]                  ;(38)
  movsd xmm2, [a]                    ;(39)
  subsd xmm0, xmm2                   ;(40)
  addsd xmm2, xmm1                   ;(41)
  movsd [rdi], xmm1                  ;(42)
  movsd [rsi], xmm0                  ;(43)
  mulsd xmm0, xmm2                   ;(44)
  ret                                ;(45)
                                     ;(46)
section .data                        ;(47)
  a dq 2.0                           ;(48)
  b dq -3.0                          ;(49)
